# Generated by Django 4.1.2 on 2023-05-04 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_storage', models.JSONField(blank=True, null=True, verbose_name='Хранение дат')),
            ],
            options={
                'verbose_name': 'Календарь',
                'verbose_name_plural': 'Календари',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_to_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата:Время начала'),
        ),
        migrations.AddField(
            model_name='progress',
            name='id_course',
            field=models.CharField(default=0, max_length=31, verbose_name='ID course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='unchecked_lessons',
            field=models.JSONField(blank=True, null=True, verbose_name='Непросмотренные уроки'),
        ),
        migrations.AddField(
            model_name='course',
            name='calendar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course', to='school_app.calendar'),
        ),
    ]
