# Generated by Django 4.1.2 on 2022-10-29 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_user_registered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Прогресс по курсу', 'verbose_name_plural': 'Прогресс по курсам'},
        ),
        migrations.RemoveField(
            model_name='progress',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='progress',
            name='is_bought',
            field=models.BooleanField(default=False, verbose_name='Куплено'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='status_tasks',
            field=models.CharField(default=' ', max_length=8192, verbose_name='Задачи курса (статус)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 20, 23, 9, 720187), verbose_name='Зарегистрировался'),
        ),
    ]
