# Generated by Django 4.1.2 on 2022-11-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0016_notification_delete_push_alter_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='answer_tasks',
            field=models.CharField(default=' ', max_length=4096, verbose_name='Ответы на задания'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='status_tasks',
            field=models.CharField(default=' ', max_length=2048, verbose_name='Задачи курса (статус)'),
        ),
    ]
